### ISSUE TITLE
[効果検証]CausualImpactの実装練習を行う

### ISSUE THREAD

**Issue by KoseiN38** [KoseiN38/pj_study#10]
// Template name
[効果検証]CausualImpactの実装練習を行う

// About 
#8 

// Template content
## Overview
CausualImpactの実装練習を兼ねて、「新型コロナウイルスの感染者数の推移」のデータを使って効果検証を行う。

対象とする施策としては、政府が行った緊急事態宣言があげられる。

> 1回目の緊急事態宣言：2020/4/7(火)～2020/5/25(木)
2回目の緊急事態宣言：2021/1/8(金)～2021/3/21(日)
3回目の緊急事態宣言：2021/4/25(日)～2021/6/20(日)

上記３回分それぞれの施策に対して、感染者数が減少傾向にあるのかどうか介入前後のデータを使って推定を行う。

なお、あくまで手法の実装練習のため、精度は追わない。そのためこちらでは、推定に使用するモデル・共変量選定はこだわらない。

## Purpose
Describe the purpose of this issue
ex) To style it.

## Task
Break down and manage your tasks.
- [x] データの読み込み（[こちら](https://www.mhlw.go.jp/stf/covid-19/open-data.html)より）
- [x] 特徴量の作成（[`year`, `month`, `day`, `week`, `Y`, `log_Y`, `Z`]
- [x] 回帰モデルの作成(対数も併せて２モデル）
- [ ] 介入のあったグループの介入のなかった場合の感染者数推移の推定
- [x] #11
- [x] 介入有無によるグラフのプロット（感染者数推移、実測値と予測値の乖離）

**Comment by KoseiN38** [comment]
結果

- 施策（緊急事態宣言）によって、１～３回のいずれも感染者数は減少する傾向にあった。
- 実際の効果量の推移でみると、１～３回のいずれも序盤（発令より２週間当たり）は特に減少傾向にあるが、中盤→終盤にかけて介入によってむしろ増加傾向にあると予測されている。
- 上記、効果量が分岐する期間幅は、１→２→３回の施策ごとに小さくなっている。つまり、１回目では施策より２週間後に効果増減が分岐しているが、３回目になると施策より３，４日ですでに効果増減が分岐している。

考察
- 緊急事態宣言発令により、発令のなかった同期間と比較すると平均的に減少する傾向にある。
- 平均的に減少傾向がある一方で、発令より数週間（もしくは数日）経つと、発令することによってむしろ増加してくる傾向がみられる。おそらく、発令により人の移動の制限があった分、反動によって発令のなかった場合と比べると移動が増えるために増加したものと思われる。つまりより短期ベースで施策を打つことが考えられる。
- 緊急事態宣言の回を増すごとに、効果量の分岐地点が早っている。あまり頻繁に緊急事態宣言を行うと効果が薄まる傾向にある。人々が緊急事態宣言下の感覚に慣れてきていると考えられる。
